const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),dns=require('dns').promises,net=require('net');
const root=__dirname,port=process.env.PORT||8080;
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const STREAMS={sami:'https://s2.radio.co/s0dc6b5c9b/listen',fix:'https://n06a-eu.rcs.revma.com/gnys6kxst8tvv',prl:'https://stream.rcs.revma.com/prfmwmwy768uv'};
const agents={http:new http.Agent({keepAlive:true,maxSockets:100}),https:new https.Agent({keepAlive:true,maxSockets:100})};
function json(res,code,obj){if(res.headersSent)return res.destroy();res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))}
function privateIP(ip){if(net.isIP(ip)===4){const a=ip.split('.').map(Number);return a[0]===10||a[0]===127||a[0]===0||a[0]===169&&a[1]===254||a[0]===172&&a[1]>=16&&a[1]<=31||a[0]===192&&a[1]===168}return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:')}
async function safeUrl(raw){let u;try{u=new URL(raw)}catch{return null}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;if(u.port&&!['80','443'].includes(u.port))return null;try{const addrs=await dns.lookup(u.hostname,{all:true});if(!addrs.length||addrs.some(a=>privateIP(a.address)))return null}catch{return null}return u}
async function proxyStream(req,res,raw,depth=0){if(depth>6)return json(res,502,{error:'too_many_redirects'});const u=await safeUrl(raw);if(!u)return json(res,400,{error:'invalid_stream_url'});const lib=u.protocol==='https:'?https:http;const up=lib.get(u,{headers:{'User-Agent':'Mozilla/5.0 RadioID/17','Icy-MetaData':'0','Accept':'audio/*,*/*;q=.5','Accept-Encoding':'identity'},agent:u.protocol==='https:'?agents.https:agents.http},r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location){r.resume();return proxyStream(req,res,new URL(r.headers.location,u).toString(),depth+1)}if(r.statusCode<200||r.statusCode>=300){r.resume();return json(res,502,{error:'upstream_'+r.statusCode})}res.writeHead(200,{'content-type':r.headers['content-type']||'audio/mpeg','cache-control':'no-store','access-control-allow-origin':'*'});res.flushHeaders?.();r.pipe(res);const close=()=>r.destroy();req.once('aborted',close);res.once('close',close)});up.setTimeout(20000,()=>up.destroy());up.on('error',()=>{if(!res.headersSent)json(res,502,{error:'stream_unavailable'});else res.destroy()})}

async function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>200000){reject(new Error('body_too_large'));req.destroy()}});req.on('end',()=>resolve(b));req.on('error',reject)})}
function capture(raw,seconds=12,depth=0){return new Promise(async(resolve,reject)=>{if(depth>6)return reject(new Error('too_many_redirects'));const u=await safeUrl(raw);if(!u)return reject(new Error('invalid_stream_url'));const lib=u.protocol==='https:'?https:http;let chunks=[],bytes=0,finished=false,timer;
const done=(err,data)=>{if(finished)return;finished=true;clearTimeout(timer);err?reject(err):resolve(data)};
const q=lib.get(u,{headers:{'User-Agent':'Mozilla/5.0 RadioID-Recognition/17','Icy-MetaData':'0','Accept':'audio/*,*/*;q=.5','Accept-Encoding':'identity'},agent:u.protocol==='https:'?agents.https:agents.http},r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location){r.resume();q.destroy();capture(new URL(r.headers.location,u).toString(),seconds,depth+1).then(resolve,reject);return}if(r.statusCode<200||r.statusCode>=300){r.resume();return done(new Error('upstream_'+r.statusCode))}r.on('data',c=>{chunks.push(c);bytes+=c.length;if(bytes>8*1024*1024){r.destroy();done(null,Buffer.concat(chunks))}});r.on('end',()=>done(null,Buffer.concat(chunks)));timer=setTimeout(()=>{r.destroy();done(null,Buffer.concat(chunks))},seconds*1000)});q.setTimeout(15000,()=>q.destroy(new Error('stream_timeout')));q.on('error',e=>done(e))})}
function auddRecognize(buf){return new Promise((resolve,reject)=>{const token=process.env.AUDD_API_TOKEN;if(!token)return reject(new Error('AUDD_API_TOKEN_missing'));const boundary='----RadioID'+Date.now().toString(16);const pre=Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="api_token"\r\n\r\n${token}\r\n--${boundary}\r\nContent-Disposition: form-data; name="return"\r\n\r\napple_music,spotify\r\n--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="radio.mp3"\r\nContent-Type: audio/mpeg\r\n\r\n`);const post=Buffer.from(`\r\n--${boundary}--\r\n`);const body=Buffer.concat([pre,buf,post]);const q=https.request('https://api.audd.io/',{method:'POST',headers:{'Content-Type':`multipart/form-data; boundary=${boundary}`,'Content-Length':body.length,'User-Agent':'RadioID/17'}},r=>{let out='';r.on('data',c=>out+=c);r.on('end',()=>{try{resolve(JSON.parse(out))}catch{reject(new Error('invalid_audd_response'))}})});q.setTimeout(30000,()=>q.destroy(new Error('audd_timeout')));q.on('error',reject);q.end(body)})}
async function recognize(req,res){try{const body=await readBody(req);let p={};try{p=body?JSON.parse(body):{}}catch{return json(res,400,{ok:false,error:'invalid_json'})}let raw=p.url;if(p.station&&STREAMS[p.station])raw=STREAMS[p.station];if(!raw)return json(res,400,{ok:false,error:'missing_stream'});const clip=await capture(raw,12);if(clip.length<4096)return json(res,502,{ok:false,error:'audio_clip_too_small'});const a=await auddRecognize(clip);if(a.status!=='success')return json(res,502,{ok:false,error:'audd_error',details:a.error||null});if(!a.result)return json(res,200,{ok:true,found:false,message:'Nie rozpoznano utworu. Spróbuj ponownie za chwilę.'});const x=a.result;return json(res,200,{ok:true,found:true,artist:x.artist,title:x.title,album:x.album||null,release_date:x.release_date||null,song_link:x.song_link||null,spotify:x.spotify?.external_urls?.spotify||null,apple_music:x.apple_music?.url||null})}catch(e){return json(res,502,{ok:false,error:e.message||'recognition_failed'})}}
function serve(req,res,p){let f=path.join(root,p==='/'?'index.html':p);if(!f.startsWith(root))return res.writeHead(403).end();fs.stat(f,(e,st)=>{if(e||!st.isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream','cache-control':'no-cache, no-store, must-revalidate'});fs.createReadStream(f).pipe(res)})}
http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return json(res,200,{ok:true,app:'Radio ID v17 recognition',auddConfigured:!!process.env.AUDD_API_TOKEN});if(u.pathname==='/api/recognize'&&req.method==='POST')return recognize(req,res);const m=u.pathname.match(/^\/api\/stream\/(sami|fix|prl)$/);if(m)return proxyStream(req,res,STREAMS[m[1]]);if(u.pathname==='/api/stream'){const raw=u.searchParams.get('url');if(!raw)return json(res,400,{error:'missing_url'});return proxyStream(req,res,raw)}serve(req,res,u.pathname)}).listen(port,'0.0.0.0',()=>console.log(`Radio ID v17: http://0.0.0.0:${port}`));
